# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b4ecf751235acd8c828f16247bb782d469e9de0f6b25f0a41773c50ba9394f972f5c0b457d77599109ae1f4271433c5a72151b3a847c3a79b57255d2ab8e58

test:
  secret_key_base: 8bde79eaa5f673fee870abd03b6446817747e3e0b5361ce2689eedeb8a8efc3933378492499bf905de1d9dbc23076586574fecb74474f2573e96f2425d27b8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
